- toolbox
Having quick access to the hosts /run directory is helpful for
troubleshooting. Additionally this provides access to the docker socket
from within the toolbox.
> feat(toolbox): bind /run into toolbox container

- toolbox
I am running CoreOS out of RAM, thus I need to tell toolbox where to store the images.
> Make toolbox data directory configurable

- toolbox
This makes it a bit easier to see what exactly is going on (and review
any changes in future)
> toolbox: split nspawn command to multiple lines

- toolbox
Abort the `toolbox` script immediately if an error occurs rather than ignoring them.
> Abort script on error

- toolbox
Saves a few extra cycles of not needing to spawn the container process anymore. Just wait to assemble the rootfs layers.
> refactor(toolbox): use docker create instead

- toolbox
Allow Toolbox users to set custom volume mounts and have sensible defaults.
Tools like sysdig expect volumes to be mounted to set directories which are
not compatible with the hard coded defaults.
> feat(toolbox) Allow custom Volume mounts

- toolbox
Allow users to set custom environment vars. This is useful when
toolbox is used with custom TOOLBOX_DOCKER_IMAGE. Since toolbox
doesn't recognize the 'ENV' lines from Dockerfile of the image.
Also, add the ability to provide system-wide defaults.
> allow custom environment vars

- toolbox
Using 24 works around a bug in 25 that prevents `dnf` from working unless you import the Fedora GPG key, which is hard to instruct users to do due to the interactive nature of toolbox
cc: @dm0-
> default to Fedora 24

- toolbox
Use an arm64 docker image when running on an arm64 machine.
No official arm64 Fedora docker image is currently available, so use an
Ubuntu image.
Fixes https://github.com/coreos/bugs/issues/1754 (/usr/bin/toolbox fails on ARMv8 with "execv() failed: Exec format error" on 1235.2.0/ARMv8).
> Add arm64 support

- toolbox
Since systemd v233 fixed the SIGKILL problems, use Fedora's latest image again.
And proxy environment variables were blocked from `rkt` by `sudo`, so explicitly pass them through.
This fixes coreos/bugs#1869.
> Update the image and support environment variables

- toolbox
This is a workaround for when toolbox is used as a login shell, and that user then passes a command directly to SSH.  SSH handles the situation by calling "toolbox -c 'the whole command'", which can be used by passing arguments to a POSIX shell in the toolbox container (and hoping the user didn't pick a container without one).
This fixes coreos/bugs#899.
> toolbox: make toolbox understand the -c shell command option

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
This will cause GitHub's "New issue" button to redirect to a template chooser.
> github: add issue reporting templates

- README.md
- rhcos-toolbox
- rhcos-toolbox.spec
Add rhcos-toolbox and corresponding specfile for building wtih rdgo.
rhcos-toolbox is a script that makes use of podman to create a
privileged debug/admin container, with ability to handle user
defined commands and variables. Modify README to reflect the change.
> Add toolbox script for RHCOS

- rhcos-toolbox
Change default image to redhat registry support-tools image for
debugging, as well as add the ability to runlabel directly if
the RUN label exists in the image.
Signed-off-by: Yu Qi Zhang <jerzhang@redhat.com>
> rhcos-toolbox: fix default and add runlabel

- toolbox
Since the last systemd update, nspawn now warns about using the `--share-system` option.  Instead switch to the catch-all environment variable which has the same effect.
> toolbox: Switch --share-system to the environment

- rhcos-toolbox
Implements https://bugzilla.redhat.com/show_bug.cgi?id=1792423#c0 which will allow `HTTP_PROXY` and `HTTPS_PROXY` to pass through to `podman`.
> rhcos-toolbox: Pass env to sudo when required

- rhcos-toolbox
After the initial execution of toolbox, subsequent executions
would fail because the interactive flag is missing.  The user is
left with a shell prompt but cannot type anything.
> rhcos-toolbox: use interactive flag for exec

- rhcos-toolbox
Using a Fedora image instead of the RHEL support tools image for
toolbox was causing an error only when running from an `oc debug
node` pod.  There are no issues when running directly on RHEL
CoreOS.  Adding the podman `--pid=host` option fixes the error
but only when usding `podman run`.  There seems to be a difference
between `podman run` and `podman create`, `podman start`, and
`podman exec`.
There was also a difference on the second invocation of toolbox if
a container was already created.  The first invocation would use
the images' CMD and the second would use /bin/sh if no command was
passed in.  The second invocation will now use the images' CMD
when executing into the container for a more consistent experience.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1850230
> rhcos-toolbox: use same options for non default images

- README.md
Bugs should now be reported in this repo, not in the Container Linux bug tracker.
> README: stop directing issues to old bug tracker

- rhcos-toolbox
podman displays '\<no value\>' when a label is not set for a container
image.
Fixes: https://github.com/coreos/toolbox/commit/a6d2ecf4d4d7f2c5313f8c0807197f0949f6ea16
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1924020
> rhcos-toolbox: Ignore podman '<no value>' output for empty labels

- rhcos-toolbox
`podman` returns `<no value>` when inspecting a label that does not
exist. That string is interpreted as the presence of a RUN label, so
we try to start the container with a non-existent RUN label. Use some
go formatting to return an empty string when the label is empty.
We've somehow avoided this until it was reported in RHBZ#2048789.
Co-authored-by: Jonathan Lebon <jonathan@jlebon.com>
> rhcos-toolbox: check for an empty RUN label

- rhcos-toolbox
If a toolbox container image has been pulled to a node, it may get out
of date over time. This adds a check to see if there is a newere
toolbox container image available and prompts the user to download it.
Closes: RHBZ#2049591
> rhcos-toolbox: add ability to check if a newer image is available

- rhcos-toolbox
-container_runlabel and container_run functions modified to initiate
'podman container create' which is followed by 'podman start' and 'podman exec'.
-container_exec function modified to keep the arguments as an array for avoiding
the issue of commands with multiple arguments or spaces.
Partially revert/undo: https://github.com/coreos/toolbox/commit/d510461986ff7fe8160614ba5cf179f8facacdda
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2039589
> Bug 2039589: Toolbox command ignores the first time

- rhcos-toolbox
This is a pile of improvements that started with just fixing how we handle the authfile, but has grown to things like:
- removing existing containers when new container image is used
- being specific about `podman container inspect` and `podman image inspect`
- normalizing the use of `${var}` format
See the individual commits for more details.
> Improvements to authfile handling, podman inspect, variable formats

- rhcos-toolbox
The `toolbox` command reports that the container is in an unknown
state `created`. Addressed the issue by adding the state 'created'
in the conditional statements of the toolbox state.
Resolves JIRA: https://issues.redhat.com/browse/OCPBUGSM-45019
Bugzilla : https://bugzilla.redhat.com/show_bug.cgi?id=2093040
> Bug 2093040: Unable to start `toolbox` on RHCOS using `podman` 4.0

- rhcos-toolbox
Workaround for a bug in podman when using podman exec with nested
containers. This particularly happen when running `oc debug node ...`
and then running a container with toolbox.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1915537
---
Clean-up stdout and keep all misc messages on stderr
---
Add some comments
> Bug 1915537: Rework to use podman attach instead of exec

- rhcos-toolbox
Allow HTTP_PROXY and HTTPS_PROXY to pass through to skopeo.
Closes: #83 
Signed-off-by: Kenneth D'souza <kennethdsouza94@gmail.com>
> rhcos-toolbox(skopeo): Pass env to sudo when required

- rhcos-toolbox
```
In ./rhcos-toolbox line 21:
source "${TOOLBOXRC}"
^------------^ SC1090 (warning): ShellCheck can't follow non-constant source. Use a directive to specify location.
In ./rhcos-toolbox line 48:
local runlabel=$(image_runlabel)
^------^ SC2155 (warning): Declare and assign separately to avoid masking return values.
In ./rhcos-toolbox line 63:
local state=$(container_state)
^---^ SC2155 (warning): Declare and assign separately to avoid masking return values.
In ./rhcos-toolbox line 183:
echo "${@}; exit" | sudo podman attach "${TOOLBOX_NAME}"
^--^ SC2145 (error): Argument mixes string and array. Use * or separate argument.
```
> Fix ShellCheck errors and warnings
